//! Flag-setting arithmetic, logic, shift/rotate, multiply/divide and BCD
//! primitives. Instruction handlers call these with operand values; operand
//! plumbing lives in `modrm.rs`/`execute.rs`.
//!
//! Each width (8/16/32-bit) gets its own concrete, inlinable set of
//! functions, generated by one macro — no runtime width dispatch, per the
//! speed-to-the-maximum goal.
//!
//! Unlike the 8086, the 386 masks shift/rotate counts to 5 bits and runs
//! them through a barrel shifter, so wide counts are computed directly in
//! 64-bit arithmetic instead of iterating. Where the 386 leaves a flag
//! *undefined* we set a fixed, deterministic value; the SingleStepTests
//! harness masks those bits.

use super::Cpu;
use super::registers::EFlags;

macro_rules! alu_width {
    ($t:ty, $wide:ty, $swide:ty, $sign:literal, $bits:literal, $szp:ident,
     $add:ident, $adc:ident, $sub:ident, $sbb:ident, $and:ident, $or:ident, $xor:ident,
     $inc:ident, $dec:ident, $neg:ident,
     $rol:ident, $ror:ident, $rcl:ident, $rcr:ident, $shl:ident, $shr:ident, $sar:ident) => {
        impl Cpu {
            #[inline]
            pub(crate) fn $add(&mut self, a: $t, b: $t) -> $t {
                let r = a.wrapping_add(b);
                let f = &mut self.regs.eflags;
                f.set(EFlags::CF, r < a);
                f.set(EFlags::AF, (a ^ b ^ r) & 0x10 != 0);
                f.set(EFlags::OF, (a ^ r) & (b ^ r) & $sign != 0);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $adc(&mut self, a: $t, b: $t) -> $t {
                let c = self.regs.eflags.contains(EFlags::CF) as $t;
                let r = a.wrapping_add(b).wrapping_add(c);
                let f = &mut self.regs.eflags;
                f.set(
                    EFlags::CF,
                    (a as $wide) + (b as $wide) + (c as $wide) > <$t>::MAX as $wide,
                );
                f.set(EFlags::AF, (a ^ b ^ r) & 0x10 != 0);
                f.set(EFlags::OF, (a ^ r) & (b ^ r) & $sign != 0);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $sub(&mut self, a: $t, b: $t) -> $t {
                let r = a.wrapping_sub(b);
                let f = &mut self.regs.eflags;
                f.set(EFlags::CF, b > a);
                f.set(EFlags::AF, (a ^ b ^ r) & 0x10 != 0);
                f.set(EFlags::OF, (a ^ b) & (a ^ r) & $sign != 0);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $sbb(&mut self, a: $t, b: $t) -> $t {
                let c = self.regs.eflags.contains(EFlags::CF) as $t;
                let r = a.wrapping_sub(b).wrapping_sub(c);
                let f = &mut self.regs.eflags;
                f.set(EFlags::CF, (b as $wide) + (c as $wide) > a as $wide);
                f.set(EFlags::AF, (a ^ b ^ r) & 0x10 != 0);
                f.set(EFlags::OF, (a ^ b) & (a ^ r) & $sign != 0);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $and(&mut self, a: $t, b: $t) -> $t {
                let r = a & b;
                let f = &mut self.regs.eflags;
                f.remove(EFlags::CF | EFlags::OF | EFlags::AF);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $or(&mut self, a: $t, b: $t) -> $t {
                let r = a | b;
                let f = &mut self.regs.eflags;
                f.remove(EFlags::CF | EFlags::OF | EFlags::AF);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $xor(&mut self, a: $t, b: $t) -> $t {
                let r = a ^ b;
                let f = &mut self.regs.eflags;
                f.remove(EFlags::CF | EFlags::OF | EFlags::AF);
                f.$szp(r);
                r
            }

            /// `INC`: like add-1 but `CF` is preserved.
            #[inline]
            pub(crate) fn $inc(&mut self, a: $t) -> $t {
                let r = a.wrapping_add(1);
                let f = &mut self.regs.eflags;
                f.set(EFlags::AF, a & 0xF == 0xF);
                f.set(EFlags::OF, r == $sign);
                f.$szp(r);
                r
            }

            /// `DEC`: like sub-1 but `CF` is preserved.
            #[inline]
            pub(crate) fn $dec(&mut self, a: $t) -> $t {
                let r = a.wrapping_sub(1);
                let f = &mut self.regs.eflags;
                f.set(EFlags::AF, a & 0xF == 0);
                f.set(EFlags::OF, a == $sign);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $neg(&mut self, a: $t) -> $t {
                let r = (0 as $t).wrapping_sub(a);
                let f = &mut self.regs.eflags;
                f.set(EFlags::CF, a != 0);
                f.set(EFlags::AF, a & 0xF != 0);
                f.set(EFlags::OF, a == $sign);
                f.$szp(r);
                r
            }

            // Shifts and rotates. The 386 masks the count to 5 bits *before* the
            // zero-count check (count 0 leaves all flags untouched) and shifts
            // through a barrel shifter, modeled here with 64-bit arithmetic. OF is
            // architecturally defined only for count 1 but always computed the same
            // way; AF after shifts is undefined (cleared here).

            #[inline]
            pub(crate) fn $shl(&mut self, v: $t, count: u32) -> $t {
                let n = count & 31;
                if n == 0 {
                    return v;
                }
                let wide = (v as u64) << n;
                let r = wide as $t;
                let f = &mut self.regs.eflags;
                // A count that is a multiple of the operand width pulls CF from the
                // replicated byte lane of the 32-bit shifter (e.g. SHL AL,16 gives
                // CF = bit 0) - 386 behavior asserted by the hardware suite.
                let cf = if n % $bits == 0 {
                    v & 1 != 0
                } else {
                    wide >> $bits & 1 != 0
                };
                f.set(EFlags::CF, cf);
                f.set(EFlags::OF, (r & $sign != 0) != cf);
                f.remove(EFlags::AF);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $shr(&mut self, v: $t, count: u32) -> $t {
                let n = count & 31;
                if n == 0 {
                    return v;
                }
                let r = ((v as u64) >> n) as $t;
                let f = &mut self.regs.eflags;
                let cf = if n % $bits == 0 {
                    v & $sign != 0
                } else {
                    (v as u64) >> (n - 1) & 1 != 0
                };
                f.set(EFlags::CF, cf);
                // Per 1-bit step (as the shifter iterates): OF = MSB before the
                // last step — the original MSB for count 1, 0 for wider counts.
                f.set(EFlags::OF, ((v as u64) >> (n - 1)) & $sign as u64 != 0);
                f.remove(EFlags::AF);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $sar(&mut self, v: $t, count: u32) -> $t {
                let n = count & 31;
                if n == 0 {
                    return v;
                }
                let sx = v as $swide as i64;
                let r = (sx >> n) as $t;
                let f = &mut self.regs.eflags;
                f.set(EFlags::CF, sx >> (n - 1) & 1 != 0);
                f.remove(EFlags::OF | EFlags::AF);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $rol(&mut self, v: $t, count: u32) -> $t {
                let n = count & 31;
                if n == 0 {
                    return v;
                }
                let r = v.rotate_left(n % $bits);
                let f = &mut self.regs.eflags;
                let cf = r & 1 != 0;
                f.set(EFlags::CF, cf);
                f.set(EFlags::OF, (r & $sign != 0) != cf);
                r
            }

            #[inline]
            pub(crate) fn $ror(&mut self, v: $t, count: u32) -> $t {
                let n = count & 31;
                if n == 0 {
                    return v;
                }
                let r = v.rotate_right(n % $bits);
                let f = &mut self.regs.eflags;
                f.set(EFlags::CF, r & $sign != 0);
                f.set(EFlags::OF, (r ^ (r << 1)) & $sign != 0);
                r
            }

            #[inline]
            pub(crate) fn $rcl(&mut self, v: $t, count: u32) -> $t {
                // The 386 iterates the full masked count (no mod-9/17 reduction);
                // the rotation is periodic but the flags track the true last step.
                let n = count & 31;
                if n == 0 {
                    return v;
                }
                let mut r = v;
                for _ in 0..n {
                    let c = r & $sign != 0;
                    r = (r << 1) | self.regs.eflags.contains(EFlags::CF) as $t;
                    self.regs.eflags.set(EFlags::CF, c);
                }
                let cf = self.regs.eflags.contains(EFlags::CF);
                self.regs.eflags.set(EFlags::OF, (r & $sign != 0) != cf);
                r
            }

            #[inline]
            pub(crate) fn $rcr(&mut self, v: $t, count: u32) -> $t {
                let n = count & 31;
                if n == 0 {
                    return v;
                }
                let mut r = v;
                for _ in 0..n {
                    // Per 1-bit step: OF = MSB XOR CF, computed *before* the rotate.
                    let cf = self.regs.eflags.contains(EFlags::CF);
                    self.regs.eflags.set(EFlags::OF, (r & $sign != 0) != cf);
                    let c = r & 1 != 0;
                    r = (r >> 1) | (cf as $t) << ($bits - 1);
                    self.regs.eflags.set(EFlags::CF, c);
                }
                r
            }
        }
    };
}

alu_width!(
    u8, u16, i8, 0x80, 8, set_szp8, add8, adc8, sub8, sbb8, and8, or8, xor8, inc8, dec8, neg8,
    rol8, ror8, rcl8, rcr8, shl8, shr8, sar8
);
alu_width!(
    u16, u32, i16, 0x8000, 16, set_szp16, add16, adc16, sub16, sbb16, and16, or16, xor16, inc16,
    dec16, neg16, rol16, ror16, rcl16, rcr16, shl16, shr16, sar16
);
alu_width!(
    u32,
    u64,
    i32,
    0x8000_0000,
    32,
    set_szp32,
    add32,
    adc32,
    sub32,
    sbb32,
    and32,
    or32,
    xor32,
    inc32,
    dec32,
    neg32,
    rol32,
    ror32,
    rcl32,
    rcr32,
    shl32,
    shr32,
    sar32
);

impl Cpu {
    // --- Multiply -------------------------------------------------------------
    // CF/OF are the architecturally defined flags (set when the result does
    // not fit the destination half); SZAP are undefined on real hardware and
    // set deterministically from the low half here.

    pub(crate) fn mul8(&mut self, v: u8) {
        let r = (self.regs.reg8(0) as u16) * v as u16;
        self.regs.set_reg16(0, r);
        let hi = r & 0xFF00 != 0;
        self.regs.eflags.set(EFlags::CF, hi);
        self.regs.eflags.set(EFlags::OF, hi);
        self.regs.eflags.remove(EFlags::AF);
        self.regs.eflags.set_szp8(r as u8);
    }

    pub(crate) fn mul16(&mut self, v: u16) {
        let r = (self.regs.reg16(0) as u32) * v as u32;
        self.regs.set_reg16(0, r as u16);
        self.regs.set_reg16(2, (r >> 16) as u16);
        let hi = r & 0xFFFF_0000 != 0;
        self.regs.eflags.set(EFlags::CF, hi);
        self.regs.eflags.set(EFlags::OF, hi);
        self.regs.eflags.remove(EFlags::AF);
        self.regs.eflags.set_szp16(r as u16);
    }

    pub(crate) fn mul32(&mut self, v: u32) {
        let r = (self.regs.gpr[0] as u64) * v as u64;
        self.regs.gpr[0] = r as u32;
        self.regs.gpr[2] = (r >> 32) as u32;
        let hi = r >> 32 != 0;
        self.regs.eflags.set(EFlags::CF, hi);
        self.regs.eflags.set(EFlags::OF, hi);
        self.regs.eflags.remove(EFlags::AF);
        self.regs.eflags.set_szp32(r as u32);
    }

    pub(crate) fn imul8(&mut self, v: u8) {
        let r = (self.regs.reg8(0) as i8 as i16) * (v as i8 as i16);
        self.regs.set_reg16(0, r as u16);
        let over = r != r as i8 as i16;
        self.regs.eflags.set(EFlags::CF, over);
        self.regs.eflags.set(EFlags::OF, over);
        self.regs.eflags.remove(EFlags::AF);
        self.regs.eflags.set_szp8(r as u8);
    }

    pub(crate) fn imul16(&mut self, v: u16) {
        let r = (self.regs.reg16(0) as i16 as i32) * (v as i16 as i32);
        self.regs.set_reg16(0, r as u16);
        self.regs.set_reg16(2, (r >> 16) as u16);
        let over = r != r as i16 as i32;
        self.regs.eflags.set(EFlags::CF, over);
        self.regs.eflags.set(EFlags::OF, over);
        self.regs.eflags.remove(EFlags::AF);
        self.regs.eflags.set_szp16(r as u16);
    }

    pub(crate) fn imul32(&mut self, v: u32) {
        let r = (self.regs.gpr[0] as i32 as i64) * (v as i32 as i64);
        self.regs.gpr[0] = r as u32;
        self.regs.gpr[2] = (r >> 32) as u32;
        let over = r != r as i32 as i64;
        self.regs.eflags.set(EFlags::CF, over);
        self.regs.eflags.set(EFlags::OF, over);
        self.regs.eflags.remove(EFlags::AF);
        self.regs.eflags.set_szp32(r as u32);
    }

    /// Truncating signed multiply (`IMUL r, r/m [, imm]`): returns the low
    /// half and sets CF/OF on signed overflow of the truncation.
    pub(crate) fn imul_trunc16(&mut self, a: u16, b: u16) -> u16 {
        let r = (a as i16 as i32) * (b as i16 as i32);
        let over = r != r as i16 as i32;
        self.regs.eflags.set(EFlags::CF, over);
        self.regs.eflags.set(EFlags::OF, over);
        self.regs.eflags.remove(EFlags::AF);
        self.regs.eflags.set_szp16(r as u16);
        r as u16
    }

    pub(crate) fn imul_trunc32(&mut self, a: u32, b: u32) -> u32 {
        let r = (a as i32 as i64) * (b as i32 as i64);
        let over = r != r as i32 as i64;
        self.regs.eflags.set(EFlags::CF, over);
        self.regs.eflags.set(EFlags::OF, over);
        self.regs.eflags.remove(EFlags::AF);
        self.regs.eflags.set_szp32(r as u32);
        r as u32
    }

    // --- Divide -----------------------------------------------------------------
    // Returns `false` on a divide fault (#DE: divisor zero or quotient
    // overflow); the caller raises the exception. All flags are left
    // untouched (they are undefined on hardware and masked by the suite).

    #[must_use]
    pub(crate) fn div8(&mut self, v: u8) -> bool {
        if v == 0 {
            return false;
        }
        let dividend = self.regs.reg16(0);
        let q = dividend / v as u16;
        if q > 0xFF {
            return false;
        }
        self.regs.set_reg8(0, q as u8);
        self.regs.set_reg8(4, (dividend % v as u16) as u8);
        true
    }

    #[must_use]
    pub(crate) fn idiv8(&mut self, v: u8) -> bool {
        if v == 0 {
            return false;
        }
        let dividend = self.regs.reg16(0) as i16;
        // Negating the minimum dividend overflows the internal negate: #DE.
        if dividend == i16::MIN {
            return false;
        }
        let (q, r) = idiv_lossy8(dividend.unsigned_abs(), (v as i8).unsigned_abs() as u16);
        let neg = (dividend < 0) != ((v as i8) < 0);
        // Sign check on the lossy quotient; exactly -128 is admitted.
        let quot = if neg {
            if q > 0x80 {
                return false;
            }
            q.wrapping_neg()
        } else {
            if q >= 0x80 {
                return false;
            }
            q
        };
        let rem = if dividend < 0 { r.wrapping_neg() } else { r };
        self.regs.set_reg8(0, quot);
        self.regs.set_reg8(4, rem);
        true
    }

    #[must_use]
    pub(crate) fn div16(&mut self, v: u16) -> bool {
        if v == 0 {
            return false;
        }
        let dividend = (self.regs.reg16(2) as u32) << 16 | self.regs.reg16(0) as u32;
        let q = dividend / v as u32;
        if q > 0xFFFF {
            return false;
        }
        self.regs.set_reg16(0, q as u16);
        self.regs.set_reg16(2, (dividend % v as u32) as u16);
        true
    }

    #[must_use]
    pub(crate) fn idiv16(&mut self, v: u16) -> bool {
        if v == 0 {
            return false;
        }
        let dividend = ((self.regs.reg16(2) as u32) << 16 | self.regs.reg16(0) as u32) as i32;
        if dividend == i32::MIN {
            return false;
        }
        let (q, r) = idiv_lossy16(dividend.unsigned_abs(), (v as i16).unsigned_abs() as u32);
        let neg = (dividend < 0) != ((v as i16) < 0);
        let quot = if neg {
            if q > 0x8000 {
                return false;
            }
            q.wrapping_neg()
        } else {
            if q >= 0x8000 {
                return false;
            }
            q
        };
        let rem = if dividend < 0 { r.wrapping_neg() } else { r };
        self.regs.set_reg16(0, quot);
        self.regs.set_reg16(2, rem);
        true
    }

    #[must_use]
    pub(crate) fn div32(&mut self, v: u32) -> bool {
        if v == 0 {
            return false;
        }
        let dividend = (self.regs.gpr[2] as u64) << 32 | self.regs.gpr[0] as u64;
        let q = dividend / v as u64;
        if q > 0xFFFF_FFFF {
            return false;
        }
        self.regs.gpr[0] = q as u32;
        self.regs.gpr[2] = (dividend % v as u64) as u32;
        true
    }

    #[must_use]
    pub(crate) fn idiv32(&mut self, v: u32) -> bool {
        if v == 0 {
            return false;
        }
        let dividend = ((self.regs.gpr[2] as u64) << 32 | self.regs.gpr[0] as u64) as i64;
        if dividend == i64::MIN {
            return false;
        }
        let (q, r) = idiv_lossy32(dividend.unsigned_abs(), (v as i32).unsigned_abs() as u64);
        let neg = (dividend < 0) != ((v as i32) < 0);
        let quot = if neg {
            if q > 0x8000_0000 {
                return false;
            }
            q.wrapping_neg()
        } else {
            if q >= 0x8000_0000 {
                return false;
            }
            q
        };
        let rem = if dividend < 0 { r.wrapping_neg() } else { r };
        self.regs.gpr[0] = quot;
        self.regs.gpr[2] = rem;
        true
    }

    // --- BCD adjustments ---------------------------------------------------------
    // The 386 keeps the 8086 microcode behavior (notably the AF-dependent
    // 0x9F threshold in DAA/DAS and AAA/AAS adjusting AL and AH separately),
    // as asserted by the SingleStepTests 386 suite. Flags the suite masks
    // (OF, and SZP for AAA/AAS) are still set deterministically.

    pub(crate) fn daa(&mut self) {
        // Unlike the 8086 there is no AF-dependent 0x9F threshold: the 386
        // follows the documented 0x99 rule (asserted by the test suite).
        let old_al = self.regs.reg8(0);
        let old_cf = self.regs.eflags.contains(EFlags::CF);
        let mut al = old_al;
        if old_al & 0xF > 9 || self.regs.eflags.contains(EFlags::AF) {
            al = al.wrapping_add(6);
            self.regs.eflags.insert(EFlags::AF);
        } else {
            self.regs.eflags.remove(EFlags::AF);
        }
        if old_al > 0x99 || old_cf {
            al = al.wrapping_add(0x60);
            self.regs.eflags.insert(EFlags::CF);
        } else {
            self.regs.eflags.remove(EFlags::CF);
        }
        self.regs.eflags.remove(EFlags::OF);
        self.regs.eflags.set_szp8(al);
        self.regs.set_reg8(0, al);
    }

    pub(crate) fn das(&mut self) {
        let old_al = self.regs.reg8(0);
        let old_cf = self.regs.eflags.contains(EFlags::CF);
        let mut al = old_al;
        let mut cf = false;
        if old_al & 0xF > 9 || self.regs.eflags.contains(EFlags::AF) {
            // CF absorbs the borrow of the AL-6 step (386 behavior).
            cf = old_cf || old_al < 6;
            al = al.wrapping_sub(6);
            self.regs.eflags.insert(EFlags::AF);
        } else {
            self.regs.eflags.remove(EFlags::AF);
        }
        if old_al > 0x99 || old_cf {
            al = al.wrapping_sub(0x60);
            cf = true;
        }
        self.regs.eflags.set(EFlags::CF, cf);
        self.regs.eflags.remove(EFlags::OF);
        self.regs.eflags.set_szp8(al);
        self.regs.set_reg8(0, al);
    }

    pub(crate) fn aaa(&mut self) {
        // Unlike the 8086, the 386 follows the `AX += 0x106` pseudocode
        // exactly (AL's carry propagates into AH).
        let al = self.regs.reg8(0);
        if al & 0xF > 9 || self.regs.eflags.contains(EFlags::AF) {
            let ax = self.regs.reg16(0).wrapping_add(0x106);
            self.regs.set_reg16(0, ax);
            self.regs.eflags.insert(EFlags::AF | EFlags::CF);
        } else {
            self.regs.eflags.remove(EFlags::AF | EFlags::CF);
        }
        let masked = self.regs.reg8(0) & 0x0F;
        self.regs.set_reg8(0, masked);
        self.regs.eflags.remove(EFlags::OF);
        self.regs.eflags.set_szp8(masked);
    }

    pub(crate) fn aas(&mut self) {
        let al = self.regs.reg8(0);
        if al & 0xF > 9 || self.regs.eflags.contains(EFlags::AF) {
            let ax = self.regs.reg16(0).wrapping_sub(0x106);
            self.regs.set_reg16(0, ax);
            self.regs.eflags.insert(EFlags::AF | EFlags::CF);
        } else {
            self.regs.eflags.remove(EFlags::AF | EFlags::CF);
        }
        let masked = self.regs.reg8(0) & 0x0F;
        self.regs.set_reg8(0, masked);
        self.regs.eflags.remove(EFlags::OF);
        self.regs.eflags.set_szp8(masked);
    }

    /// `AAM base` (D4 ib). Returns `false` on base 0 (#DE) — with the flag
    /// state the divider leaves behind (only PF set of the SZP group).
    #[must_use]
    pub(crate) fn aam(&mut self, base: u8) -> bool {
        if base == 0 {
            // The divide-by-zero flag state exposes the divider's internal
            // path: PF follows the parity of AL*0x81 (AL plus AL's low bit
            // rotated to the top), per the hardware captures.
            let pf = (self.regs.reg8(0).wrapping_mul(0x81))
                .count_ones()
                .is_multiple_of(2);
            self.regs
                .eflags
                .remove(EFlags::CF | EFlags::OF | EFlags::AF | EFlags::SF | EFlags::ZF);
            self.regs.eflags.set(EFlags::PF, pf);
            return false;
        }
        let al = self.regs.reg8(0);
        self.regs.set_reg8(4, al / base);
        self.regs.set_reg8(0, al % base);
        self.regs
            .eflags
            .remove(EFlags::CF | EFlags::OF | EFlags::AF);
        self.regs.eflags.set_szp8(al % base);
        true
    }

    /// `AAD base` (D5 ib).
    pub(crate) fn aad(&mut self, base: u8) {
        let al = self
            .regs
            .reg8(0)
            .wrapping_add(self.regs.reg8(4).wrapping_mul(base));
        self.regs.set_reg16(0, al as u16);
        self.regs
            .eflags
            .remove(EFlags::CF | EFlags::OF | EFlags::AF);
        self.regs.eflags.set_szp8(al);
    }
}

/// Generate the 386's signed-division core: a restoring divide whose
/// remainder register is exactly W bits, so a bit shifted past the top is
/// LOST instead of forcing a subtract. This only matters for overflowing
/// quotients (|divisor| <= 2^(W-1) after negation), where it produces the
/// hardware's escaped-#DE results (e.g. a quotient of exactly -2^(W-1)).
macro_rules! idiv_lossy {
    ($name:ident, $t:ty, $wide:ty, $bits:literal) => {
        fn $name(dividend: $wide, divisor: $wide) -> ($t, $t) {
            let mut r = (dividend >> $bits) as $t;
            let lo = dividend as $t;
            let mut q: $t = 0;
            for i in (0..$bits).rev() {
                // The shift out of bit W-1 is lost (plain wrapping shl).
                r = (r << 1) | ((lo >> i) & 1);
                if r as $wide >= divisor {
                    r -= divisor as $t;
                    q |= 1 << i;
                }
            }
            (q, r)
        }
    };
}

idiv_lossy!(idiv_lossy8, u8, u16, 8);
idiv_lossy!(idiv_lossy16, u16, u32, 16);
idiv_lossy!(idiv_lossy32, u32, u64, 32);
