//! Flag-setting arithmetic, logic, shift/rotate, multiply/divide and BCD
//! primitives. Instruction handlers call these with operand values; operand
//! plumbing lives in `modrm.rs`/`execute.rs`.
//!
//! Each width (8/16/32/64-bit) gets its own concrete, inlinable set of
//! functions, generated by one macro — no runtime width dispatch, per the
//! speed-to-the-maximum goal.
//!
//! Shift/rotate counts are masked to 5 bits (6 for 64-bit operands) before
//! anything happens, per the architecture. Where hardware leaves a flag
//! *undefined* this core sets a fixed, deterministic value that matches
//! common modern silicon where that is known; no conformance suite exists
//! for x86-64 to pin these, unlike the 8088/80386 cores.

use super::Cpu;
use super::registers::RFlags;

macro_rules! alu_width {
    ($t:ty, $wide:ty, $swide:ty, $sign:literal, $bits:literal, $cmask:literal, $szp:ident,
     $add:ident, $adc:ident, $sub:ident, $sbb:ident, $and:ident, $or:ident, $xor:ident,
     $inc:ident, $dec:ident, $neg:ident,
     $rol:ident, $ror:ident, $rcl:ident, $rcr:ident, $shl:ident, $shr:ident, $sar:ident) => {
        impl Cpu {
            #[inline]
            pub(crate) fn $add(&mut self, a: $t, b: $t) -> $t {
                let r = a.wrapping_add(b);
                let f = &mut self.regs.rflags;
                f.set(RFlags::CF, r < a);
                f.set(RFlags::AF, (a ^ b ^ r) & 0x10 != 0);
                f.set(RFlags::OF, (a ^ r) & (b ^ r) & $sign != 0);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $adc(&mut self, a: $t, b: $t) -> $t {
                let c = self.regs.rflags.contains(RFlags::CF) as $t;
                let r = a.wrapping_add(b).wrapping_add(c);
                let f = &mut self.regs.rflags;
                f.set(
                    RFlags::CF,
                    (a as $wide) + (b as $wide) + (c as $wide) > <$t>::MAX as $wide,
                );
                f.set(RFlags::AF, (a ^ b ^ r) & 0x10 != 0);
                f.set(RFlags::OF, (a ^ r) & (b ^ r) & $sign != 0);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $sub(&mut self, a: $t, b: $t) -> $t {
                let r = a.wrapping_sub(b);
                let f = &mut self.regs.rflags;
                f.set(RFlags::CF, b > a);
                f.set(RFlags::AF, (a ^ b ^ r) & 0x10 != 0);
                f.set(RFlags::OF, (a ^ b) & (a ^ r) & $sign != 0);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $sbb(&mut self, a: $t, b: $t) -> $t {
                let c = self.regs.rflags.contains(RFlags::CF) as $t;
                let r = a.wrapping_sub(b).wrapping_sub(c);
                let f = &mut self.regs.rflags;
                f.set(RFlags::CF, (b as $wide) + (c as $wide) > a as $wide);
                f.set(RFlags::AF, (a ^ b ^ r) & 0x10 != 0);
                f.set(RFlags::OF, (a ^ b) & (a ^ r) & $sign != 0);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $and(&mut self, a: $t, b: $t) -> $t {
                let r = a & b;
                let f = &mut self.regs.rflags;
                f.remove(RFlags::CF | RFlags::OF | RFlags::AF);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $or(&mut self, a: $t, b: $t) -> $t {
                let r = a | b;
                let f = &mut self.regs.rflags;
                f.remove(RFlags::CF | RFlags::OF | RFlags::AF);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $xor(&mut self, a: $t, b: $t) -> $t {
                let r = a ^ b;
                let f = &mut self.regs.rflags;
                f.remove(RFlags::CF | RFlags::OF | RFlags::AF);
                f.$szp(r);
                r
            }

            /// `INC`: like add-1 but `CF` is preserved.
            #[inline]
            pub(crate) fn $inc(&mut self, a: $t) -> $t {
                let r = a.wrapping_add(1);
                let f = &mut self.regs.rflags;
                f.set(RFlags::AF, a & 0xF == 0xF);
                f.set(RFlags::OF, r == $sign);
                f.$szp(r);
                r
            }

            /// `DEC`: like sub-1 but `CF` is preserved.
            #[inline]
            pub(crate) fn $dec(&mut self, a: $t) -> $t {
                let r = a.wrapping_sub(1);
                let f = &mut self.regs.rflags;
                f.set(RFlags::AF, a & 0xF == 0);
                f.set(RFlags::OF, a == $sign);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $neg(&mut self, a: $t) -> $t {
                let r = (0 as $t).wrapping_sub(a);
                let f = &mut self.regs.rflags;
                f.set(RFlags::CF, a != 0);
                f.set(RFlags::AF, a & 0xF != 0);
                f.set(RFlags::OF, a == $sign);
                f.$szp(r);
                r
            }

            // Shifts and rotates. The count is masked (5 bits, 6 for 64-bit
            // operands) *before* the zero-count check — count 0 leaves all
            // flags untouched. OF is architecturally defined only for count 1
            // but always computed by the count-1 rule here; AF after shifts
            // is undefined on hardware (cleared here).

            #[inline]
            pub(crate) fn $shl(&mut self, v: $t, count: u32) -> $t {
                let n = count & $cmask;
                if n == 0 {
                    return v;
                }
                // 128-bit shift: wide enough for every operand width that the
                // masked count can exceed (a byte shifted by 31, say).
                let wide = (v as u128) << n;
                let r = wide as $t;
                let f = &mut self.regs.rflags;
                // CF is the last bit shifted out; a count beyond the operand
                // width leaves 0 (the wide shift models that directly).
                let cf = wide >> $bits & 1 != 0;
                f.set(RFlags::CF, cf);
                f.set(RFlags::OF, (r & $sign != 0) != cf);
                f.remove(RFlags::AF);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $shr(&mut self, v: $t, count: u32) -> $t {
                let n = count & $cmask;
                if n == 0 {
                    return v;
                }
                let r = if n >= $bits { 0 } else { v >> n };
                let f = &mut self.regs.rflags;
                let cf = n <= $bits && (v as $wide) >> (n - 1) & 1 != 0;
                f.set(RFlags::CF, cf);
                // Count-1 rule: OF = MSB of the original value.
                f.set(RFlags::OF, v & $sign != 0);
                f.remove(RFlags::AF);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $sar(&mut self, v: $t, count: u32) -> $t {
                let n = count & $cmask;
                if n == 0 {
                    return v;
                }
                let sx = v as $swide;
                let r = (sx >> (n - 1).min($bits - 1) >> 1) as $t;
                let f = &mut self.regs.rflags;
                f.set(RFlags::CF, sx >> (n - 1).min($bits - 1) & 1 != 0);
                f.remove(RFlags::OF | RFlags::AF);
                f.$szp(r);
                r
            }

            #[inline]
            pub(crate) fn $rol(&mut self, v: $t, count: u32) -> $t {
                let n = count & $cmask;
                if n == 0 {
                    return v;
                }
                let r = v.rotate_left(n % $bits);
                let f = &mut self.regs.rflags;
                let cf = r & 1 != 0;
                f.set(RFlags::CF, cf);
                f.set(RFlags::OF, (r & $sign != 0) != cf);
                r
            }

            #[inline]
            pub(crate) fn $ror(&mut self, v: $t, count: u32) -> $t {
                let n = count & $cmask;
                if n == 0 {
                    return v;
                }
                let r = v.rotate_right(n % $bits);
                let f = &mut self.regs.rflags;
                f.set(RFlags::CF, r & $sign != 0);
                f.set(RFlags::OF, (r ^ (r << 1)) & $sign != 0);
                r
            }

            #[inline]
            pub(crate) fn $rcl(&mut self, v: $t, count: u32) -> $t {
                // Modern CPUs reduce the masked count modulo width+1 (the
                // carry participates in the rotation), unlike the 386.
                let n = (count & $cmask) % ($bits + 1);
                if n == 0 {
                    return v;
                }
                let c = self.regs.rflags.contains(RFlags::CF) as $wide;
                // Rotate the (width+1)-bit value v:CF left by n.
                let x = ((v as $wide) << 1) | c;
                let w = $bits + 1;
                let rot = ((x << n) | (x >> (w - n))) & ((1 as $wide) << w).wrapping_sub(1);
                let r = (rot >> 1) as $t;
                let cf = rot & 1 != 0;
                let f = &mut self.regs.rflags;
                f.set(RFlags::CF, cf);
                f.set(RFlags::OF, (r & $sign != 0) != cf);
                r
            }

            #[inline]
            pub(crate) fn $rcr(&mut self, v: $t, count: u32) -> $t {
                let n = (count & $cmask) % ($bits + 1);
                if n == 0 {
                    return v;
                }
                let c = self.regs.rflags.contains(RFlags::CF) as $wide;
                let x = ((v as $wide) << 1) | c;
                let w = $bits + 1;
                let rot = ((x >> n) | (x << (w - n))) & ((1 as $wide) << w).wrapping_sub(1);
                let r = (rot >> 1) as $t;
                let cf = rot & 1 != 0;
                // Count-1 rule, computed before the rotate: OF = MSB ^ CF-in.
                self.regs
                    .rflags
                    .set(RFlags::OF, (v & $sign != 0) != (c != 0));
                self.regs.rflags.set(RFlags::CF, cf);
                r
            }
        }
    };
}

alu_width!(
    u8, u16, i8, 0x80, 8, 31, set_szp8, add8, adc8, sub8, sbb8, and8, or8, xor8, inc8, dec8, neg8,
    rol8, ror8, rcl8, rcr8, shl8, shr8, sar8
);
alu_width!(
    u16, u32, i16, 0x8000, 16, 31, set_szp16, add16, adc16, sub16, sbb16, and16, or16, xor16,
    inc16, dec16, neg16, rol16, ror16, rcl16, rcr16, shl16, shr16, sar16
);
alu_width!(
    u32,
    u64,
    i32,
    0x8000_0000,
    32,
    31,
    set_szp32,
    add32,
    adc32,
    sub32,
    sbb32,
    and32,
    or32,
    xor32,
    inc32,
    dec32,
    neg32,
    rol32,
    ror32,
    rcl32,
    rcr32,
    shl32,
    shr32,
    sar32
);
alu_width!(
    u64,
    u128,
    i64,
    0x8000_0000_0000_0000,
    64,
    63,
    set_szp64,
    add64,
    adc64,
    sub64,
    sbb64,
    and64,
    or64,
    xor64,
    inc64,
    dec64,
    neg64,
    rol64,
    ror64,
    rcl64,
    rcr64,
    shl64,
    shr64,
    sar64
);

impl Cpu {
    // --- Multiply -------------------------------------------------------------
    // CF/OF are the architecturally defined flags (set when the result does
    // not fit the destination half); SZAP are undefined on real hardware and
    // set deterministically from the low half here.

    pub(crate) fn mul8(&mut self, v: u8) {
        let r = (self.gpr8(0) as u16) * v as u16;
        self.regs.set_reg16(0, r);
        let hi = r & 0xFF00 != 0;
        self.regs.rflags.set(RFlags::CF, hi);
        self.regs.rflags.set(RFlags::OF, hi);
        self.regs.rflags.remove(RFlags::AF);
        self.regs.rflags.set_szp8(r as u8);
    }

    pub(crate) fn mul16(&mut self, v: u16) {
        let r = (self.regs.reg16(0) as u32) * v as u32;
        self.regs.set_reg16(0, r as u16);
        self.regs.set_reg16(2, (r >> 16) as u16);
        let hi = r & 0xFFFF_0000 != 0;
        self.regs.rflags.set(RFlags::CF, hi);
        self.regs.rflags.set(RFlags::OF, hi);
        self.regs.rflags.remove(RFlags::AF);
        self.regs.rflags.set_szp16(r as u16);
    }

    pub(crate) fn mul32(&mut self, v: u32) {
        let r = (self.regs.reg32(0) as u64) * v as u64;
        self.regs.set_reg32(0, r as u32);
        self.regs.set_reg32(2, (r >> 32) as u32);
        let hi = r >> 32 != 0;
        self.regs.rflags.set(RFlags::CF, hi);
        self.regs.rflags.set(RFlags::OF, hi);
        self.regs.rflags.remove(RFlags::AF);
        self.regs.rflags.set_szp32(r as u32);
    }

    pub(crate) fn mul64(&mut self, v: u64) {
        let r = (self.regs.gpr[0] as u128) * v as u128;
        self.regs.gpr[0] = r as u64;
        self.regs.gpr[2] = (r >> 64) as u64;
        let hi = r >> 64 != 0;
        self.regs.rflags.set(RFlags::CF, hi);
        self.regs.rflags.set(RFlags::OF, hi);
        self.regs.rflags.remove(RFlags::AF);
        self.regs.rflags.set_szp64(r as u64);
    }

    pub(crate) fn imul8(&mut self, v: u8) {
        let r = (self.gpr8(0) as i8 as i16) * (v as i8 as i16);
        self.regs.set_reg16(0, r as u16);
        let over = r != r as i8 as i16;
        self.regs.rflags.set(RFlags::CF, over);
        self.regs.rflags.set(RFlags::OF, over);
        self.regs.rflags.remove(RFlags::AF);
        self.regs.rflags.set_szp8(r as u8);
    }

    pub(crate) fn imul16(&mut self, v: u16) {
        let r = (self.regs.reg16(0) as i16 as i32) * (v as i16 as i32);
        self.regs.set_reg16(0, r as u16);
        self.regs.set_reg16(2, (r >> 16) as u16);
        let over = r != r as i16 as i32;
        self.regs.rflags.set(RFlags::CF, over);
        self.regs.rflags.set(RFlags::OF, over);
        self.regs.rflags.remove(RFlags::AF);
        self.regs.rflags.set_szp16(r as u16);
    }

    pub(crate) fn imul32(&mut self, v: u32) {
        let r = (self.regs.reg32(0) as i32 as i64) * (v as i32 as i64);
        self.regs.set_reg32(0, r as u32);
        self.regs.set_reg32(2, (r >> 32) as u32);
        let over = r != r as i32 as i64;
        self.regs.rflags.set(RFlags::CF, over);
        self.regs.rflags.set(RFlags::OF, over);
        self.regs.rflags.remove(RFlags::AF);
        self.regs.rflags.set_szp32(r as u32);
    }

    pub(crate) fn imul64(&mut self, v: u64) {
        let r = (self.regs.gpr[0] as i64 as i128) * (v as i64 as i128);
        self.regs.gpr[0] = r as u64;
        self.regs.gpr[2] = (r >> 64) as u64;
        let over = r != r as i64 as i128;
        self.regs.rflags.set(RFlags::CF, over);
        self.regs.rflags.set(RFlags::OF, over);
        self.regs.rflags.remove(RFlags::AF);
        self.regs.rflags.set_szp64(r as u64);
    }

    /// Truncating signed multiply (`IMUL r, r/m [, imm]`): returns the low
    /// half and sets CF/OF on signed overflow of the truncation.
    pub(crate) fn imul_trunc16(&mut self, a: u16, b: u16) -> u16 {
        let r = (a as i16 as i32) * (b as i16 as i32);
        let over = r != r as i16 as i32;
        self.regs.rflags.set(RFlags::CF, over);
        self.regs.rflags.set(RFlags::OF, over);
        self.regs.rflags.remove(RFlags::AF);
        self.regs.rflags.set_szp16(r as u16);
        r as u16
    }

    pub(crate) fn imul_trunc32(&mut self, a: u32, b: u32) -> u32 {
        let r = (a as i32 as i64) * (b as i32 as i64);
        let over = r != r as i32 as i64;
        self.regs.rflags.set(RFlags::CF, over);
        self.regs.rflags.set(RFlags::OF, over);
        self.regs.rflags.remove(RFlags::AF);
        self.regs.rflags.set_szp32(r as u32);
        r as u32
    }

    pub(crate) fn imul_trunc64(&mut self, a: u64, b: u64) -> u64 {
        let r = (a as i64 as i128) * (b as i64 as i128);
        let over = r != r as i64 as i128;
        self.regs.rflags.set(RFlags::CF, over);
        self.regs.rflags.set(RFlags::OF, over);
        self.regs.rflags.remove(RFlags::AF);
        self.regs.rflags.set_szp64(r as u64);
        r as u64
    }

    // --- Divide -----------------------------------------------------------------
    // Returns `false` on a divide fault (#DE: divisor zero or quotient
    // overflow); the caller raises the exception. All flags are left
    // untouched (undefined on hardware). Unlike the 386, x86-64 silicon
    // performs exact overflow checks — no lossy-remainder quirk.

    #[must_use]
    pub(crate) fn div8(&mut self, v: u8) -> bool {
        if v == 0 {
            return false;
        }
        let dividend = self.regs.reg16(0);
        let q = dividend / v as u16;
        if q > 0xFF {
            return false;
        }
        self.set_gpr8(0, q as u8);
        self.set_gpr8(4, (dividend % v as u16) as u8);
        true
    }

    #[must_use]
    pub(crate) fn idiv8(&mut self, v: u8) -> bool {
        if v == 0 {
            return false;
        }
        let dividend = self.regs.reg16(0) as i16;
        let q = dividend.wrapping_div(v as i8 as i16);
        if q != q as i8 as i16 || (dividend == i16::MIN && v as i8 == -1) {
            return false;
        }
        let r = dividend.wrapping_rem(v as i8 as i16);
        self.set_gpr8(0, q as u8);
        self.set_gpr8(4, r as u8);
        true
    }

    #[must_use]
    pub(crate) fn div16(&mut self, v: u16) -> bool {
        if v == 0 {
            return false;
        }
        let dividend = (self.regs.reg16(2) as u32) << 16 | self.regs.reg16(0) as u32;
        let q = dividend / v as u32;
        if q > 0xFFFF {
            return false;
        }
        self.regs.set_reg16(0, q as u16);
        self.regs.set_reg16(2, (dividend % v as u32) as u16);
        true
    }

    #[must_use]
    pub(crate) fn idiv16(&mut self, v: u16) -> bool {
        if v == 0 {
            return false;
        }
        let dividend = ((self.regs.reg16(2) as u32) << 16 | self.regs.reg16(0) as u32) as i32;
        let q = dividend.wrapping_div(v as i16 as i32);
        if q != q as i16 as i32 {
            return false;
        }
        let r = dividend.wrapping_rem(v as i16 as i32);
        self.regs.set_reg16(0, q as u16);
        self.regs.set_reg16(2, r as u16);
        true
    }

    #[must_use]
    pub(crate) fn div32(&mut self, v: u32) -> bool {
        if v == 0 {
            return false;
        }
        let dividend = (self.regs.reg32(2) as u64) << 32 | self.regs.reg32(0) as u64;
        let q = dividend / v as u64;
        if q > 0xFFFF_FFFF {
            return false;
        }
        self.regs.set_reg32(0, q as u32);
        self.regs.set_reg32(2, (dividend % v as u64) as u32);
        true
    }

    #[must_use]
    pub(crate) fn idiv32(&mut self, v: u32) -> bool {
        if v == 0 {
            return false;
        }
        let dividend = ((self.regs.reg32(2) as u64) << 32 | self.regs.reg32(0) as u64) as i64;
        let q = dividend.wrapping_div(v as i32 as i64);
        if q != q as i32 as i64 {
            return false;
        }
        let r = dividend.wrapping_rem(v as i32 as i64);
        self.regs.set_reg32(0, q as u32);
        self.regs.set_reg32(2, r as u32);
        true
    }

    #[must_use]
    pub(crate) fn div64(&mut self, v: u64) -> bool {
        if v == 0 {
            return false;
        }
        let dividend = (self.regs.gpr[2] as u128) << 64 | self.regs.gpr[0] as u128;
        let q = dividend / v as u128;
        if q > u64::MAX as u128 {
            return false;
        }
        self.regs.gpr[0] = q as u64;
        self.regs.gpr[2] = (dividend % v as u128) as u64;
        true
    }

    #[must_use]
    pub(crate) fn idiv64(&mut self, v: u64) -> bool {
        if v == 0 {
            return false;
        }
        let dividend = ((self.regs.gpr[2] as u128) << 64 | self.regs.gpr[0] as u128) as i128;
        let q = dividend.wrapping_div(v as i64 as i128);
        if q != q as i64 as i128 {
            return false;
        }
        let r = dividend.wrapping_rem(v as i64 as i128);
        self.regs.gpr[0] = q as u64;
        self.regs.gpr[2] = r as u64;
        true
    }

    // --- BCD adjustments ---------------------------------------------------------
    // Legacy/compat modes only (#UD in 64-bit mode, enforced at dispatch).
    // These follow the documented pseudocode; the undefined flags get the
    // same deterministic values the 386 core uses.

    pub(crate) fn daa(&mut self) {
        let old_al = self.gpr8(0);
        let old_cf = self.regs.rflags.contains(RFlags::CF);
        let mut al = old_al;
        if old_al & 0xF > 9 || self.regs.rflags.contains(RFlags::AF) {
            al = al.wrapping_add(6);
            self.regs.rflags.insert(RFlags::AF);
        } else {
            self.regs.rflags.remove(RFlags::AF);
        }
        if old_al > 0x99 || old_cf {
            al = al.wrapping_add(0x60);
            self.regs.rflags.insert(RFlags::CF);
        } else {
            self.regs.rflags.remove(RFlags::CF);
        }
        self.regs.rflags.remove(RFlags::OF);
        self.regs.rflags.set_szp8(al);
        self.set_gpr8(0, al);
    }

    pub(crate) fn das(&mut self) {
        let old_al = self.gpr8(0);
        let old_cf = self.regs.rflags.contains(RFlags::CF);
        let mut al = old_al;
        let mut cf = false;
        if old_al & 0xF > 9 || self.regs.rflags.contains(RFlags::AF) {
            cf = old_cf || old_al < 6;
            al = al.wrapping_sub(6);
            self.regs.rflags.insert(RFlags::AF);
        } else {
            self.regs.rflags.remove(RFlags::AF);
        }
        if old_al > 0x99 || old_cf {
            al = al.wrapping_sub(0x60);
            cf = true;
        }
        self.regs.rflags.set(RFlags::CF, cf);
        self.regs.rflags.remove(RFlags::OF);
        self.regs.rflags.set_szp8(al);
        self.set_gpr8(0, al);
    }

    pub(crate) fn aaa(&mut self) {
        let al = self.gpr8(0);
        if al & 0xF > 9 || self.regs.rflags.contains(RFlags::AF) {
            let ax = self.regs.reg16(0).wrapping_add(0x106);
            self.regs.set_reg16(0, ax);
            self.regs.rflags.insert(RFlags::AF | RFlags::CF);
        } else {
            self.regs.rflags.remove(RFlags::AF | RFlags::CF);
        }
        let masked = self.gpr8(0) & 0x0F;
        self.set_gpr8(0, masked);
        self.regs.rflags.remove(RFlags::OF);
        self.regs.rflags.set_szp8(masked);
    }

    pub(crate) fn aas(&mut self) {
        let al = self.gpr8(0);
        if al & 0xF > 9 || self.regs.rflags.contains(RFlags::AF) {
            let ax = self.regs.reg16(0).wrapping_sub(0x106);
            self.regs.set_reg16(0, ax);
            self.regs.rflags.insert(RFlags::AF | RFlags::CF);
        } else {
            self.regs.rflags.remove(RFlags::AF | RFlags::CF);
        }
        let masked = self.gpr8(0) & 0x0F;
        self.set_gpr8(0, masked);
        self.regs.rflags.remove(RFlags::OF);
        self.regs.rflags.set_szp8(masked);
    }

    /// `AAM base` (D4 ib). Returns `false` on base 0 (#DE).
    #[must_use]
    pub(crate) fn aam(&mut self, base: u8) -> bool {
        if base == 0 {
            self.regs
                .rflags
                .remove(RFlags::CF | RFlags::OF | RFlags::AF | RFlags::SF);
            self.regs.rflags.insert(RFlags::ZF | RFlags::PF);
            return false;
        }
        let al = self.gpr8(0);
        self.set_gpr8(4, al / base);
        self.set_gpr8(0, al % base);
        self.regs
            .rflags
            .remove(RFlags::CF | RFlags::OF | RFlags::AF);
        self.regs.rflags.set_szp8(al % base);
        true
    }

    /// `AAD base` (D5 ib).
    pub(crate) fn aad(&mut self, base: u8) {
        let al = self.gpr8(0).wrapping_add(self.gpr8(4).wrapping_mul(base));
        self.regs.set_reg16(0, al as u16);
        self.regs
            .rflags
            .remove(RFlags::CF | RFlags::OF | RFlags::AF);
        self.regs.rflags.set_szp8(al);
    }
}
